### PR TITLE
add EmoteClip

### PR DESCRIPTION
**Pull request by kiemfp**
the code is just an test
can you make it function please?

### CODE REVIEW

**Comment by kiemfp** [comment]
oh in the first that opened an pull and issue

**Comment by Spencer0187** [comment]
What do you even mean by emote clip? /e dance2 emote clip? /e laugh?

**Comment by kiemfp** [comment]
the one that you do the /e dance2 and wait for the end of the animation, move the camera in an certain position and enter in first person or do an shiftlock.

**Comment by Spencer0187** [comment]
that is so trivial and easy to do... why... hell, if you want, just bind the dance2 to any key using "unequip com" with the slot set to "0", and then shiftlock yourself.

**Comment by kiemfp** [comment]
bruh

**Pull request closed without merging**
